#!/bin/bash
# write-changelog.sh - prepend a release section to CHANGELOG.md.
#
# Deliberately not git-cliff or a third-party action: the release job holds
# contents:write, so every dependency it pulls is a supply-chain risk, and the
# grouping we need is a dozen lines of shell. Fewer moving parts also means the
# release cannot fail because an action changed its interface.
#
# Usage: write-changelog.sh <version> [<previous-tag>]
#
# With no previous tag, every commit reachable from HEAD is included.
#
# Portability: macOS bash 3.2 with BSD userland, and Linux with GNU userland.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

VERSION="${1:-}"
PREV_TAG="${2:-}"
[ -n "$VERSION" ] || { echo "ERROR: usage: write-changelog.sh <version> [previous-tag]" >&2; exit 2; }

CHANGELOG="$REPO_ROOT/CHANGELOG.md"
TODAY="$(date -u '+%Y-%m-%d')"

if [ -n "$PREV_TAG" ]; then
  RANGE="$PREV_TAG..HEAD"
else
  RANGE="HEAD"
fi

RAW="$(mktemp)"
SECTION="$(mktemp)"
trap 'rm -f "$RAW" "$SECTION"' EXIT

git -C "$REPO_ROOT" log --no-merges --pretty=format:'%s' "$RANGE" > "$RAW"

# Emit one heading per Conventional Commit type, in a fixed order so the file
# reads consistently release to release. Types with no commits are omitted.
emit_group() {
  local pattern="$1" heading="$2" matched
  matched="$(grep -E "$pattern" "$RAW" || true)"
  [ -n "$matched" ] || return 0
  echo "### $heading" >> "$SECTION"
  echo "" >> "$SECTION"
  printf '%s\n' "$matched" | sed -E 's/^[a-z]+(\([^)]*\))?!?: */- /' >> "$SECTION"
  echo "" >> "$SECTION"
}

{
  echo "## $VERSION - $TODAY"
  echo ""
} > "$SECTION"

# Breaking changes lead: they are the reason a consumer would read this at all.
BREAKING="$(grep -E '^[a-z]+(\([^)]*\))?!:' "$RAW" || true)"
if [ -n "$BREAKING" ]; then
  echo "### Breaking changes" >> "$SECTION"
  echo "" >> "$SECTION"
  printf '%s\n' "$BREAKING" | sed -E 's/^[a-z]+(\([^)]*\))?!: */- /' >> "$SECTION"
  echo "" >> "$SECTION"
fi

# These patterns deliberately exclude "!": a breaking commit is already listed
# under "Breaking changes" above, and matching it again here would print it
# twice in the same release section.
emit_group '^feat(\([^)]*\))?: ' 'Features'
emit_group '^fix(\([^)]*\))?: ' 'Fixes'
emit_group '^(docs|refactor|perf|style)(\([^)]*\))?: ' 'Other changes'
# build/ci/chore/test/revert are grouped rather than dropped. Editing a deploy
# script under "chore:" is deployable and cuts a release, so without this the
# release notes for a real change to shipped tooling would be empty.
emit_group '^(build|ci|chore|test|revert)(\([^)]*\))?: ' 'Maintenance'

# Fall back when nothing was written, not merely when there were no commits at
# all: a release whose commits all fell outside every group above would
# otherwise publish a heading with no content under it.
if [ "$(wc -l < "$SECTION" | tr -d ' ')" -le 2 ]; then
  echo "- No user-facing changes recorded." >> "$SECTION"
  echo "" >> "$SECTION"
fi

if [ ! -f "$CHANGELOG" ]; then
  {
    echo "# Changelog"
    echo ""
    echo "Every release of this library. Versions follow [Semantic Versioning](https://semver.org):"
    echo "a major means a consumer must act, a minor adds content, a patch corrects it."
    echo ""
    echo "This file is generated by the release workflow. Do not edit it by hand."
    echo ""
  } > "$CHANGELOG"
fi

# Insert the new section directly after the preamble, so newest is first.
NEW="$(mktemp)"
awk -v section_file="$SECTION" '
  BEGIN { inserted = 0 }
  # The first "## " line is the previous release; insert above it.
  /^## / && !inserted {
    while ((getline line < section_file) > 0) print line
    inserted = 1
  }
  { print }
  END {
    if (!inserted) {
      while ((getline line < section_file) > 0) print line
    }
  }
' "$CHANGELOG" > "$NEW"
mv "$NEW" "$CHANGELOG"

echo "Prepended $VERSION to CHANGELOG.md"
